///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The JobEmployeeValidationNewData2 recording.
    /// </summary>
    [TestModule("6c2e5a33-2c45-4cbc-abfe-0e95c8cec9b7", ModuleType.Recording, 1)]
    public partial class JobEmployeeValidationNewData2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static JobEmployeeValidationNewData2 instance = new JobEmployeeValidationNewData2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public JobEmployeeValidationNewData2()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static JobEmployeeValidationNewData2 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.EditCrew' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.EditCrewInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.EditCrew.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 15s.", new RecordItemIndex(1));
            Delay.Duration(15000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Alfonz Renaldo - LABOR') on item 'ComHcssHcssmobileTesting.Content1.AlfonzRenaldoLABOR'.", repo.ComHcssHcssmobileTesting.Content1.AlfonzRenaldoLABORInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.Content1.AlfonzRenaldoLABORInfo, "Text", "Alfonz Renaldo - LABOR");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText' at Center", repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditTextInfo, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'new' on item 'ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditTextInfo, new RecordItemIndex(4));
            repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText.Element.SetAttributeValue("Text", "new");
            Delay.Milliseconds(100);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='New Employee - LABOR') on item 'ComHcssHcssmobileTesting.Content1.NewEmployeeLABOR'.", repo.ComHcssHcssmobileTesting.Content1.NewEmployeeLABORInfo, new RecordItemIndex(5));
                Validate.Attribute(repo.ComHcssHcssmobileTesting.Content1.NewEmployeeLABORInfo, "Text", "New Employee - LABOR", Validate.DefaultMessage, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
