///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The JobPayClassValidation2NewData recording.
    /// </summary>
    [TestModule("493cebfd-a080-4a5a-b72f-1d794497cef2", ModuleType.Recording, 1)]
    public partial class JobPayClassValidation2NewData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static JobPayClassValidation2NewData instance = new JobPayClassValidation2NewData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public JobPayClassValidation2NewData()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static JobPayClassValidation2NewData Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AlfonzRenaldo' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AlfonzRenaldoInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AlfonzRenaldo.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.ButtonChange' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonChangeInfo, new RecordItemIndex(1));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonChange.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='AOF') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.TextAOF'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.TextAOFInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.TextAOFInfo, "Text", "AOF");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('8') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "8");
            Delay.Milliseconds(500);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='NEWPC') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.NEWPC'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.NEWPCInfo, new RecordItemIndex(4));
                Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.NEWPCInfo, "Text", "NEWPC", Validate.DefaultMessage, false);
                Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(4)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'ComHcssHcssmobileTesting.TimeCardEntry.TimeCardEntry'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.TimeCardEntryInfo, new RecordItemIndex(5));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.TimeCardEntry.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Done1Info, new RecordItemIndex(6));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done1.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
