///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.Validation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LibraryPayClassValidationNewData recording.
    /// </summary>
    [TestModule("323bcd3a-1818-4f63-8c91-90046b6dad3b", ModuleType.Recording, 1)]
    public partial class LibraryPayClassValidationNewData : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static LibraryPayClassValidationNewData instance = new LibraryPayClassValidationNewData();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LibraryPayClassValidationNewData()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LibraryPayClassValidationNewData Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content1.SourceJob' at Center", repo.ComHcssHcssmobileTesting.Content1.SourceJobInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.Content1.SourceJob.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content1.Relative2' at Center", repo.ComHcssHcssmobileTesting.Content1.Relative2Info, new RecordItemIndex(1));
            repo.ComHcssHcssmobileTesting.Content1.Relative2.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content1.Relative3' at Center", repo.ComHcssHcssmobileTesting.Content1.Relative3Info, new RecordItemIndex(2));
            repo.ComHcssHcssmobileTesting.Content1.Relative3.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Linear1.ChangePayClass' at Center", repo.ComHcssHcssmobileTesting.Linear1.ChangePayClassInfo, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.Linear1.ChangePayClass.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='FOREMAN') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.FOREMAN'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.FOREMANInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.FOREMANInfo, "Text", "FOREMAN");
            Delay.Milliseconds(100);
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (Text='NEWLIBPC') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.NEWLIBPC'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.NEWLIBPCInfo, new RecordItemIndex(5));
                //Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.NEWLIBPCInfo, "Text", "NEWLIBPC", Validate.DefaultMessage, false);
                //Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{BACK}' press on 'ComHcssHcssmobileTesting.TimeCardEditCrew'.", repo.ComHcssHcssmobileTesting.TimeCardEditCrewInfo, new RecordItemIndex(6));
            repo.ComHcssHcssmobileTesting.TimeCardEditCrew.PressKeys("{BACK}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Done' at Center", repo.ComHcssHcssmobileTesting.DoneInfo, new RecordItemIndex(7));
            repo.ComHcssHcssmobileTesting.Done.Touch();
            Delay.Milliseconds(1000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
