///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.ExportDiaryToHDM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddEntryNote recording.
    /// </summary>
    [TestModule("96cf93c6-4196-4848-9771-524429a675fe", ModuleType.Recording, 1)]
    public partial class AddEntryNote : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static AddEntryNote instance = new AddEntryNote();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddEntryNote()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddEntryNote Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            // Add Entry Notes
            Report.Log(ReportLevel.Info, "Set Value", "Add Entry Notes\r\nSetting attribute Text to 'We worked hard today.  It started out too windy, but we made up for it.  Todd was not working so I had words with him and sent him home.   The sub did not show up with enough guys to be effective.' on item 'ComHcssHcssmobileTesting.ScrollView.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.ScrollView.AndroidWidgetEditTextInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.ScrollView.AndroidWidgetEditText.Element.SetAttributeValue("Text", "We worked hard today.  It started out too windy, but we made up for it.  Todd was not working so I had words with him and sent him home.   The sub did not show up with enough guys to be effective.");
            Delay.Milliseconds(100);
            
            // Tap out of the Entry Notes so that Quick Prases get added to the correct place
            Report.Log(ReportLevel.Info, "Touch", "Tap out of the Entry Notes so that Quick Prases get added to the correct place\r\nTouch item 'ComHcssHcssmobileTesting.ScrollView.Warm7590' at Center", repo.ComHcssHcssmobileTesting.ScrollView.Warm7590Info, new RecordItemIndex(1));
            repo.ComHcssHcssmobileTesting.ScrollView.Warm7590.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
