///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.ExportDiaryToHDM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddNoteIndexes recording.
    /// </summary>
    [TestModule("c6c7b926-98a0-426d-91b8-40b0080d62ba", ModuleType.Recording, 1)]
    public partial class AddNoteIndexes : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static AddNoteIndexes instance = new AddNoteIndexes();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddNoteIndexes()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddNoteIndexes Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            // Add ten note indexes
            Report.Log(ReportLevel.Info, "Touch", "Add ten note indexes\r\nTouch item 'ComHcssHcssmobileTesting.ScrollView.NoteIndexes' at Center", repo.ComHcssHcssmobileTesting.ScrollView.NoteIndexesInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.ScrollView.NoteIndexes.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(1));
            Delay.Duration(30000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.WeatherDelay' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.WeatherDelayInfo, new RecordItemIndex(2));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.WeatherDelay.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('2') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "2");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('10') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(4));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "10");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('13') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(5));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "13");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.VisitorInspector' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.VisitorInspectorInfo, new RecordItemIndex(6));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.VisitorInspector.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('19') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(7));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "19");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('23') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(8));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "23");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('24') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(9));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "24");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.SubcontractorIssue' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.SubcontractorIssueInfo, new RecordItemIndex(10));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.SubcontractorIssue.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('30') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(11));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "30");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('31') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(12));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "31");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.VerbalInstructionGiven' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.VerbalInstructionGivenInfo, new RecordItemIndex(13));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.VerbalInstructionGiven.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('37') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(14));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "37");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.OtherSuggestion' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.OtherSuggestionInfo, new RecordItemIndex(15));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.OtherSuggestion.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.UndergroundUtilityDamageReport' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.UndergroundUtilityDamageReportInfo, new RecordItemIndex(16));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.UndergroundUtilityDamageReport.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('39') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(17));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "39");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('47') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(18));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "47");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.ContractDocuments' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.ContractDocumentsInfo, new RecordItemIndex(19));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.ContractDocuments.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.Subcontracts' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.SubcontractsInfo, new RecordItemIndex(20));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.Subcontracts.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.Email' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.EmailInfo, new RecordItemIndex(21));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.Email.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.UtilityHitWater' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.UtilityHitWaterInfo, new RecordItemIndex(22));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.UtilityHitWater.Touch();
            Delay.Milliseconds(500);
            
            // This is to close the note index selection
            Report.Log(ReportLevel.Info, "Touch", "This is to close the note index selection\r\nTouch item 'ComHcssHcssmobileTesting.ScrollView.Warm7590' at Center", repo.ComHcssHcssmobileTesting.ScrollView.Warm7590Info, new RecordItemIndex(23));
            repo.ComHcssHcssmobileTesting.ScrollView.Warm7590.Touch();
            Delay.Milliseconds(500);
            
            // This is to close the note index selection
            Report.Log(ReportLevel.Info, "Touch", "This is to close the note index selection\r\nTouch item 'ComHcssHcssmobileTesting.AndroidWidgetTableLayout.AndroidWidgetEditText1' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetTableLayout.AndroidWidgetEditText1Info, new RecordItemIndex(24));
            repo.ComHcssHcssmobileTesting.AndroidWidgetTableLayout.AndroidWidgetEditText1.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
