///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.ExportDiaryToHDM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddQuickPhrases recording.
    /// </summary>
    [TestModule("40466234-697e-45d7-b7aa-9f547d882bc0", ModuleType.Recording, 1)]
    public partial class AddQuickPhrases : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static AddQuickPhrases instance = new AddQuickPhrases();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddQuickPhrases()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddQuickPhrases Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            // Add some Quick Phrases
            Report.Log(ReportLevel.Info, "Touch", "Add some Quick Phrases\r\nTouch item 'ComHcssHcssmobileTesting.ScrollView.QuickPhrases' at Center", repo.ComHcssHcssmobileTesting.ScrollView.QuickPhrasesInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.ScrollView.QuickPhrases.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(1));
            Delay.Duration(30000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.InspectorAccepted' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.InspectorAcceptedInfo, new RecordItemIndex(2));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.InspectorAccepted.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('4') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "4");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('7') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(4));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "7");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('8') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(5));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "8");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('16') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(6));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "16");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('19') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(7));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "19");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.Welding' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.WeldingInfo, new RecordItemIndex(8));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.Welding.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.Compaction' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.CompactionInfo, new RecordItemIndex(9));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.Compaction.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('22') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(10));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "22");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('26') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(11));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "26");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('33') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(12));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "33");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.InstallationMethod' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.InstallationMethodInfo, new RecordItemIndex(13));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.InstallationMethod.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('37') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(14));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "37");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('44') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(15));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "44");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('46') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(16));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "46");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.RFIApprovalOfShopDrawings' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.RFIApprovalOfShopDrawingsInfo, new RecordItemIndex(17));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.RFIApprovalOfShopDrawings.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('58') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(18));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "58");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('61') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(19));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "61");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.EqpArrivedBrokenDown' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.EqpArrivedBrokenDownInfo, new RecordItemIndex(20));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.EqpArrivedBrokenDown.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('73') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(21));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "73");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('76') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(22));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "76");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.NoInspector' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.NoInspectorInfo, new RecordItemIndex(23));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.NoInspector.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('77') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(24));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "77");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('85') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(25));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "85");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('90') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(26));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "90");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('99') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(27));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "99");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('102') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(28));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "102");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.SubIncorrectMaterial' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.SubIncorrectMaterialInfo, new RecordItemIndex(29));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.SubIncorrectMaterial.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('108') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(30));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "108");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('114') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(31));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "114");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.MaterialFailedSpecification' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.MaterialFailedSpecificationInfo, new RecordItemIndex(32));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.MaterialFailedSpecification.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('119') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(33));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "119");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('129') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(34));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "129");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.NeedMoreTrucks' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.NeedMoreTrucksInfo, new RecordItemIndex(35));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.NeedMoreTrucks.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.NoLostTimeAccident' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.NoLostTimeAccidentInfo, new RecordItemIndex(36));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.NoLostTimeAccident.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('140') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(37));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "140");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('144') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(38));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "144");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.VisitorNewsMedia' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.VisitorNewsMediaInfo, new RecordItemIndex(39));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.VisitorNewsMedia.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('146') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(40));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "146");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('160') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(41));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "160");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.LimitedWorkTimeTraffic' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.LimitedWorkTimeTrafficInfo, new RecordItemIndex(42));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.LimitedWorkTimeTraffic.Touch();
            Delay.Milliseconds(500);
            
            // Close the Quick Phrases
            Report.Log(ReportLevel.Info, "Touch", "Close the Quick Phrases\r\nTouch item 'ComHcssHcssmobileTesting.ScrollView.Warm7590' at Center", repo.ComHcssHcssmobileTesting.ScrollView.Warm7590Info, new RecordItemIndex(43));
            repo.ComHcssHcssmobileTesting.ScrollView.Warm7590.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
