///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.ExportDiaryToHDM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddWorkingConditions recording.
    /// </summary>
    [TestModule("557a9485-a8c2-4492-a30e-bf77c251fd04", ModuleType.Recording, 1)]
    public partial class AddWorkingConditions : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static AddWorkingConditions instance = new AddWorkingConditions();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddWorkingConditions()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddWorkingConditions Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            // Add Three working conditions
            Report.Log(ReportLevel.Info, "Touch", "Add Three working conditions\r\nTouch item 'ComHcssHcssmobileTesting.ScrollView.WorkingConditions' at Center", repo.ComHcssHcssmobileTesting.ScrollView.WorkingConditionsInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.ScrollView.WorkingConditions.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(1));
            Delay.Duration(30000, false);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.Relative4' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.Relative4Info, new RecordItemIndex(2));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.Relative4.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('3') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "3");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('7') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(4));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "7");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('9') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(5));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "9");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.Relative3' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.Relative3Info, new RecordItemIndex(6));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.Relative3.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Invoke Action", "Invoking ScrollToIndex('20') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListViewInfo, new RecordItemIndex(7));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView.Element.InvokeActionWithText("ScrollToIndex", "20");
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.NormalGround' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.NormalGroundInfo, new RecordItemIndex(8));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.NormalGround.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.ScrollView.Warm7590' at Center", repo.ComHcssHcssmobileTesting.ScrollView.Warm7590Info, new RecordItemIndex(9));
            repo.ComHcssHcssmobileTesting.ScrollView.Warm7590.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
