///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using WinForms = System.Windows.Forms;

namespace HJMobileAndroid.Recordings.ExportDiaryToHDM
{
    public partial class RemoveDiaryFromHDM
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void RemoveDiary(String ConnectionString)
        {
        	SqlConnection sqlConnection1 = new SqlConnection(ConnectionString);
			SqlCommand cmd = new SqlCommand();
			//SqlParameter param;
			
			cmd.CommandText = "dbo.RemoveDiaryFromHDM";
			cmd.CommandType = CommandType.StoredProcedure;
			
			//param = new SqlParameter("@LocalDate", Convert.ToString(System.DateTime.Today));
			//param.Direction = ParameterDirection.Input;
			//param.DbType = DbType.String;
			//cmd.Parameters.Add(param);
			                         
			cmd.Connection = sqlConnection1;

			sqlConnection1.Open();

			cmd.ExecuteNonQuery();

			sqlConnection1.Close();
			
        }

    }
}