///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.ExportDiaryToHDM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SendDiary recording.
    /// </summary>
    [TestModule("8da3c9fd-c097-4ada-a0da-bb931d5810b6", ModuleType.Recording, 1)]
    public partial class SendDiary : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static SendDiary instance = new SendDiary();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SendDiary()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SendDiary Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            // Send the Diary
            Report.Log(ReportLevel.Info, "Touch", "Send the Diary\r\nTouch item 'ComHcssHcssmobileTesting.Send' at Center", repo.ComHcssHcssmobileTesting.SendInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.Send.Touch();
            Delay.Milliseconds(500);
            
            //Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.SettingsGear' at Center", repo.ComHcssHcssmobileTesting.SettingsGearInfo, new RecordItemIndex(1));
            //repo.ComHcssHcssmobileTesting.SettingsGear.Touch();
            //Delay.Milliseconds(500);
            
            //Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Relative1' at Center", repo.ComHcssHcssmobileTesting.Relative1Info, new RecordItemIndex(2));
            //repo.ComHcssHcssmobileTesting.Relative1.Touch();
            //Delay.Milliseconds(500);
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeContains (Text>'Sent') on item 'ComHcssHcssmobileTesting.DiaryTransactionSent'.", repo.ComHcssHcssmobileTesting.DiaryTransactionSentInfo, new RecordItemIndex(3));
                //Validate.Attribute(repo.ComHcssHcssmobileTesting.DiaryTransactionSentInfo, "Text", new Regex(Regex.Escape("Sent")), Validate.DefaultMessage, false);
                //Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            //Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Home6' at Center", repo.ComHcssHcssmobileTesting.Home6Info, new RecordItemIndex(4));
            //repo.ComHcssHcssmobileTesting.Home6.Touch();
            //Delay.Milliseconds(500);
            
            //Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Home4' at Center", repo.ComHcssHcssmobileTesting.Home4Info, new RecordItemIndex(5));
            //repo.ComHcssHcssmobileTesting.Home4.Touch();
            //Delay.Milliseconds(1000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1m.", new RecordItemIndex(6));
            Delay.Duration(60000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
