///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.Job_Review
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SendAndValidate recording.
    /// </summary>
    [TestModule("83cdbb27-2509-4ebd-bacb-202ac320b5cf", ModuleType.Recording, 1)]
    public partial class SendAndValidate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static SendAndValidate instance = new SendAndValidate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SendAndValidate()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SendAndValidate Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Send23' at Center", repo.ComHcssHcssmobileTesting.Send23Info, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.Send23.Touch();
            Delay.Milliseconds(1000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeMissingProduc'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeMissingProducInfo, new RecordItemIndex(1));
            Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeMissingProducInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeMoreThan100P'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeMoreThan100PInfo, new RecordItemIndex(2));
            Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeMoreThan100PInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeHasNoNotes'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeHasNoNotesInfo, new RecordItemIndex(3));
            Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeHasNoNotesInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusEmployeesRegularHours'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusEmployeesRegularHoursInfo, new RecordItemIndex(4));
            Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusEmployeesRegularHoursInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusEmployeeListedMoreTha'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusEmployeeListedMoreThaInfo, new RecordItemIndex(5));
            Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusEmployeeListedMoreThaInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusEmployeeHoursNotSigne'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusEmployeeHoursNotSigneInfo, new RecordItemIndex(6));
            Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusEmployeeHoursNotSigneInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusScheduledTimeDoesntMa'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusScheduledTimeDoesntMaInfo, new RecordItemIndex(7));
            Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusScheduledTimeDoesntMaInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusLunchNotRecordedRegu'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusLunchNotRecordedReguInfo, new RecordItemIndex(8));
            Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusLunchNotRecordedReguInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch Gestures", "Swipe gesture with direction 'Up (270°)' starting from 'Center' with distance '100.0' with swipe duration'500ms' and step count '0' on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeMissingProduc'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeMissingProducInfo, new RecordItemIndex(9));
            repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeMissingProduc.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Up (270°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "100.0"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusBreaksNotRecorded'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusBreaksNotRecordedInfo, new RecordItemIndex(10));
            Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusBreaksNotRecordedInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusEmployeeEquipmentHasL'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusEmployeeEquipmentHasLInfo, new RecordItemIndex(11));
            Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusEmployeeEquipmentHasLInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusUnlinkedPieceOfEquipm'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusUnlinkedPieceOfEquipmInfo, new RecordItemIndex(12));
            Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusUnlinkedPieceOfEquipmInfo);
            Delay.Milliseconds(100);
            
            // these are the pop up on the time card.  I am having trouble getting them to work
            //Report.Log(ReportLevel.Info, "Validation", "these are the pop up on the time card.  I am having trouble getting them to work\r\nValidating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertFirstCostCode'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertFirstCostCodeInfo, new RecordItemIndex(13));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertFirstCostCodeInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertSecondCostCode'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertSecondCostCodeInfo, new RecordItemIndex(14));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertSecondCostCodeInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertUnlinkedEquipment'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertUnlinkedEquipmentInfo, new RecordItemIndex(15));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertUnlinkedEquipmentInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertUnlinkedEqp'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertUnlinkedEqpInfo, new RecordItemIndex(16));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertUnlinkedEqpInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertFirstSchedule'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertFirstScheduleInfo, new RecordItemIndex(17));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertFirstScheduleInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertSecondSchedule'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertSecondScheduleInfo, new RecordItemIndex(18));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertSecondScheduleInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertThirdSchedule'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertThirdScheduleInfo, new RecordItemIndex(19));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertThirdScheduleInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertFirstTotal'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertFirstTotalInfo, new RecordItemIndex(20));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertFirstTotalInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertSecondTotal'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertSecondTotalInfo, new RecordItemIndex(21));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertSecondTotalInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertThirdTotal'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertThirdTotalInfo, new RecordItemIndex(22));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertThirdTotalInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertFourthTotal'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertFourthTotalInfo, new RecordItemIndex(23));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertFourthTotalInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertSignHours'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertSignHoursInfo, new RecordItemIndex(24));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertSignHoursInfo);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='False') on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.Send'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.SendInfo, new RecordItemIndex(25));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.SendInfo, "Enabled", "False");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
