///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.Job_Review
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SolveMissingProdQty recording.
    /// </summary>
    [TestModule("c1701aef-9cf5-46f4-886c-427b0ae6b71b", ModuleType.Recording, 1)]
    public partial class SolveMissingProdQty : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static SolveMissingProdQty instance = new SolveMissingProdQty();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SolveMissingProdQty()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SolveMissingProdQty Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeMissingProduc' at Center", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeMissingProducInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertOrangePlusCostCodeMissingProduc.Touch();
            Delay.Milliseconds(500);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.AlertProductionQuantities'.", repo.ComHcssHcssmobileTesting.UIWindow.AlertProductionQuantitiesInfo, new RecordItemIndex(1));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.AlertProductionQuantitiesInfo);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertQuantity'.", repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertQuantityInfo, new RecordItemIndex(2));
            //Validate.Exists(repo.ComHcssHcssmobileTesting.UIWindow.Attendance_NonUseCodes.AlertQuantityInfo);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.UIWindow.ButtonPeriod' at Center", repo.ComHcssHcssmobileTesting.UIWindow.ButtonPeriodInfo, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.UIWindow.ButtonPeriod.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.UIWindow.NumPad1' at Center", repo.ComHcssHcssmobileTesting.UIWindow.NumPad1Info, new RecordItemIndex(4));
            repo.ComHcssHcssmobileTesting.UIWindow.NumPad1.Touch();
            Delay.Milliseconds(1000);
            
            try {
                Report.Log(ReportLevel.Info, "Touch", "(Optional Action)\r\nTouch item 'ComHcssHcssmobileTesting.Done23' at Center", repo.ComHcssHcssmobileTesting.Done23Info, new RecordItemIndex(5));
                repo.ComHcssHcssmobileTesting.Done23.Touch();
                Delay.Milliseconds(500);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(5)); }
            
            try {
                Report.Log(ReportLevel.Info, "Touch", "(Optional Action)\r\nTouch item 'ComHcssHcssmobileTesting.Copy_of_Done623' at Center", repo.ComHcssHcssmobileTesting.Copy_of_Done623Info, new RecordItemIndex(6));
                repo.ComHcssHcssmobileTesting.Copy_of_Done623.Touch();
                Delay.Milliseconds(500);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
