///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.RemoteDesktopItems
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The WaitForFilesImportIntoHDM recording.
    /// </summary>
    [TestModule("7f9fa7c5-e8ce-42d3-9eda-144d226dc413", ModuleType.Recording, 1)]
    public partial class WaitForFilesImportIntoHDM : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static WaitForFilesImportIntoHDM instance = new WaitForFilesImportIntoHDM();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public WaitForFilesImportIntoHDM()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static WaitForFilesImportIntoHDM Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5000ms.", new RecordItemIndex(0));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'QaAutomationQaAutomationRemoteD.OPWindowClass' at Center.", repo.QaAutomationQaAutomationRemoteD.OPWindowClassInfo, new RecordItemIndex(1));
            repo.QaAutomationQaAutomationRemoteD.OPWindowClass.MoveTo("Center");
            Delay.Milliseconds(200);
            
            // opening start menu to get to run program
            Report.Log(ReportLevel.Info, "Mouse", "opening start menu to get to run program\r\nMouse Left Click item 'QaAutomationQaAutomationRemoteD.OPWindowClass' at 22;28.", repo.QaAutomationQaAutomationRemoteD.OPWindowClassInfo, new RecordItemIndex(2));
            repo.QaAutomationQaAutomationRemoteD.OPWindowClass.Click(new Location(OPWindowClass_Screenshot1, "22;28", OPWindowClass_Screenshot1_Options));
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1m.", new RecordItemIndex(3));
            Delay.Duration(60000, false);
            
            // opening folder to see if files are there
            Report.Log(ReportLevel.Info, "Keyboard", "opening folder to see if files are there\r\nKey sequence 'c'.", new RecordItemIndex(4));
            Keyboard.Press("c");
            Delay.Milliseconds(300);
            
            TypeColon();
            Delay.Milliseconds(0);
            
            // opening folder to see if files are there
            Report.Log(ReportLevel.Info, "Keyboard", "opening folder to see if files are there\r\nKey sequence '\\heavyjob\\mgrcnsldsvc\\{Return}'.", new RecordItemIndex(6));
            Keyboard.Press("\\heavyjob\\mgrcnsldsvc\\{Return}");
            Delay.Milliseconds(0);
            
            // waiting until files appear
            Report.Log(ReportLevel.Info, "Validation", "waiting until files appear\r\nValidating ContainsImage (Screenshot: 'Screenshot6' with region {X=634,Y=484,Width=23,Height=44}) on item 'QaAutomationQaAutomationRemoteD.OPWindowClass1'.", repo.QaAutomationQaAutomationRemoteD.OPWindowClass1Info, new RecordItemIndex(7));
            Validate.ContainsImage(repo.QaAutomationQaAutomationRemoteD.OPWindowClass1Info, OPWindowClass1_Screenshot6, OPWindowClass1_Screenshot6_Options);
            Delay.Milliseconds(0);
            
            // waiting until files are imported
            Report.Log(ReportLevel.Info, "Validation", "waiting until files are imported\r\nValidating ContainsImage (Screenshot: 'Screenshot5' with region {X=576,Y=383,Width=53,Height=46}) on item 'QaAutomationQaAutomationRemoteD.OPWindowClass'.", repo.QaAutomationQaAutomationRemoteD.OPWindowClassInfo, new RecordItemIndex(8));
            Validate.ContainsImage(repo.QaAutomationQaAutomationRemoteD.OPWindowClassInfo, OPWindowClass_Screenshot5, OPWindowClass_Screenshot5_Options);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage OPWindowClass_Screenshot1
        { get { return repo.QaAutomationQaAutomationRemoteD.OPWindowClassInfo.GetScreenshot1(new Rectangle(5, 1037, 44, 37)); } }

        Imaging.FindOptions OPWindowClass_Screenshot1_Options
        { get { return Imaging.FindOptions.Parse("0.97;None;0,0,0,0;True;10000000;60000ms"); } }

        CompressedImage OPWindowClass1_Screenshot6
        { get { return repo.QaAutomationQaAutomationRemoteD.OPWindowClass1Info.GetScreenshot6(new Rectangle(634, 484, 23, 44)); } }

        Imaging.FindOptions OPWindowClass1_Screenshot6_Options
        { get { return Imaging.FindOptions.Parse("1;None;0,0,0,0;True;10000000;1200000ms"); } }

        CompressedImage OPWindowClass_Screenshot5
        { get { return repo.QaAutomationQaAutomationRemoteD.OPWindowClassInfo.GetScreenshot5(new Rectangle(576, 383, 53, 46)); } }

        Imaging.FindOptions OPWindowClass_Screenshot5_Options
        { get { return Imaging.FindOptions.Parse("0.98;None;0,0,0,0;True;10000000;1200000ms"); } }

#endregion
    }
#pragma warning restore 0436
}
