///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.ExportTimeCardToHDM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddCostCodeQty recording.
    /// </summary>
    [TestModule("ba0aa38a-cb8d-451a-9770-68d1a3616cd8", ModuleType.Recording, 1)]
    public partial class AddCostCodeQty : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static AddCostCodeQty instance = new AddCostCodeQty();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddCostCodeQty()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddCostCodeQty Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            // 1st cost code
            Report.Log(ReportLevel.Info, "Touch", "1st cost code\r\nTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.MobilizeEquipmentLand' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.MobilizeEquipmentLandInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.MobilizeEquipmentLand.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button1' at Center", repo.ComHcssHcssmobileTesting.Content.Button1Info, new RecordItemIndex(1));
            repo.ComHcssHcssmobileTesting.Content.Button1.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.UseSuggestedQuantities' at Center", repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantitiesInfo, new RecordItemIndex(2));
            repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantities.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Notes' at Center", repo.ComHcssHcssmobileTesting.Content.NotesInfo, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.Content.Notes.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Company note' on item 'ComHcssHcssmobileTesting.Content.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.Content.AndroidWidgetEditTextInfo, new RecordItemIndex(4));
            repo.ComHcssHcssmobileTesting.Content.AndroidWidgetEditText.Element.SetAttributeValue("Text", "Company note");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Inspector note' on item 'ComHcssHcssmobileTesting.Content.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.Content.AndroidWidgetEditText1Info, new RecordItemIndex(5));
            repo.ComHcssHcssmobileTesting.Content.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "Inspector note");
            Delay.Milliseconds(100);
            
            // 2nd Cost Code
            Report.Log(ReportLevel.Info, "Touch", "2nd Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(6));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button5' at Center", repo.ComHcssHcssmobileTesting.Content.Button5Info, new RecordItemIndex(7));
            repo.ComHcssHcssmobileTesting.Content.Button5.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(8));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(9));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(10));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.AddCostCodeTag' at Center", repo.ComHcssHcssmobileTesting.Content.AddCostCodeTagInfo, new RecordItemIndex(11));
            repo.ComHcssHcssmobileTesting.Content.AddCostCodeTag.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView4.Text1ST1stSt' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.Text1ST1stStInfo, new RecordItemIndex(12));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.Text1ST1stSt.Touch();
            Delay.Milliseconds(500);
            
            // 3rd Cost Code
            Report.Log(ReportLevel.Info, "Touch", "3rd Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(13));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button2' at Center", repo.ComHcssHcssmobileTesting.Content.Button2Info, new RecordItemIndex(14));
            repo.ComHcssHcssmobileTesting.Content.Button2.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(15));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(16));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(17));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.AddCostCodeTag' at Center", repo.ComHcssHcssmobileTesting.Content.AddCostCodeTagInfo, new RecordItemIndex(18));
            repo.ComHcssHcssmobileTesting.Content.AddCostCodeTag.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView4.Text5TH5thSt' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.Text5TH5thStInfo, new RecordItemIndex(19));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.Text5TH5thSt.Touch();
            Delay.Milliseconds(500);
            
            // 4th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "4th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(20));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.AddCostCodeTag' at Center", repo.ComHcssHcssmobileTesting.Content.AddCostCodeTagInfo, new RecordItemIndex(21));
            repo.ComHcssHcssmobileTesting.Content.AddCostCodeTag.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView4.Text10TH10thSt' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.Text10TH10thStInfo, new RecordItemIndex(22));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.Text10TH10thSt.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button1' at Center", repo.ComHcssHcssmobileTesting.Content.Button1Info, new RecordItemIndex(23));
            repo.ComHcssHcssmobileTesting.Content.Button1.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(24));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(25));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(26));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Rework' at Center", repo.ComHcssHcssmobileTesting.Content.ReworkInfo, new RecordItemIndex(27));
            repo.ComHcssHcssmobileTesting.Content.Rework.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Our rework' on item 'ComHcssHcssmobileTesting.Content.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.Content.AndroidWidgetEditTextInfo, new RecordItemIndex(28));
            repo.ComHcssHcssmobileTesting.Content.AndroidWidgetEditText.Element.SetAttributeValue("Text", "Our rework");
            Delay.Milliseconds(100);
            
            // 5th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "5th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(29));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.CheckBoxTM' at Center", repo.ComHcssHcssmobileTesting.Content.CheckBoxTMInfo, new RecordItemIndex(30));
            repo.ComHcssHcssmobileTesting.Content.CheckBoxTM.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button5' at Center", repo.ComHcssHcssmobileTesting.Content.Button5Info, new RecordItemIndex(31));
            repo.ComHcssHcssmobileTesting.Content.Button5.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(32));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(33));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'Note for the inspector' on item 'ComHcssHcssmobileTesting.Content.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.Content.AndroidWidgetEditText1Info, new RecordItemIndex(34));
            repo.ComHcssHcssmobileTesting.Content.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "Note for the inspector");
            Delay.Milliseconds(100);
            
            // 6th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "6th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(35));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.CheckBoxTM' at Center", repo.ComHcssHcssmobileTesting.Content.CheckBoxTMInfo, new RecordItemIndex(36));
            repo.ComHcssHcssmobileTesting.Content.CheckBoxTM.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Rework' at Center", repo.ComHcssHcssmobileTesting.Content.ReworkInfo, new RecordItemIndex(37));
            repo.ComHcssHcssmobileTesting.Content.Rework.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button4' at Center", repo.ComHcssHcssmobileTesting.Content.Button4Info, new RecordItemIndex(38));
            repo.ComHcssHcssmobileTesting.Content.Button4.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(39));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(40));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.UseSuggestedQuantities' at Center", repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantitiesInfo, new RecordItemIndex(41));
            repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantities.Touch();
            Delay.Milliseconds(500);
            
            // 7th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "7th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(42));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.AddCostCodeTag' at Center", repo.ComHcssHcssmobileTesting.Content.AddCostCodeTagInfo, new RecordItemIndex(43));
            repo.ComHcssHcssmobileTesting.Content.AddCostCodeTag.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView4.ST400Station400' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.ST400Station400Info, new RecordItemIndex(44));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.ST400Station400.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button6' at Center", repo.ComHcssHcssmobileTesting.Content.Button6Info, new RecordItemIndex(45));
            repo.ComHcssHcssmobileTesting.Content.Button6.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(46));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(47));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.UseSuggestedQuantities' at Center", repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantitiesInfo, new RecordItemIndex(48));
            repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantities.Touch();
            Delay.Milliseconds(500);
            
            // 8th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "8th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(49));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button5' at Center", repo.ComHcssHcssmobileTesting.Content.Button5Info, new RecordItemIndex(50));
            repo.ComHcssHcssmobileTesting.Content.Button5.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(51));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(52));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(53));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.CheckBoxTM' at Center", repo.ComHcssHcssmobileTesting.Content.CheckBoxTMInfo, new RecordItemIndex(54));
            repo.ComHcssHcssmobileTesting.Content.CheckBoxTM.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Rework' at Center", repo.ComHcssHcssmobileTesting.Content.ReworkInfo, new RecordItemIndex(55));
            repo.ComHcssHcssmobileTesting.Content.Rework.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.AddCostCodeTag' at Center", repo.ComHcssHcssmobileTesting.Content.AddCostCodeTagInfo, new RecordItemIndex(56));
            repo.ComHcssHcssmobileTesting.Content.AddCostCodeTag.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView4.WRKORD01WorkOrderHash1' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.WRKORD01WorkOrderHash1Info, new RecordItemIndex(57));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.WRKORD01WorkOrderHash1.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'This is our company note' on item 'ComHcssHcssmobileTesting.Content.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.Content.AndroidWidgetEditTextInfo, new RecordItemIndex(58));
            repo.ComHcssHcssmobileTesting.Content.AndroidWidgetEditText.Element.SetAttributeValue("Text", "This is our company note");
            Delay.Milliseconds(100);
            
            // 9th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "9th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(59));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button7' at Center", repo.ComHcssHcssmobileTesting.Content.Button7Info, new RecordItemIndex(60));
            repo.ComHcssHcssmobileTesting.Content.Button7.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(61));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(62));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(63));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.CheckBoxTM' at Center", repo.ComHcssHcssmobileTesting.Content.CheckBoxTMInfo, new RecordItemIndex(64));
            repo.ComHcssHcssmobileTesting.Content.CheckBoxTM.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.AddCostCodeTag' at Center", repo.ComHcssHcssmobileTesting.Content.AddCostCodeTagInfo, new RecordItemIndex(65));
            repo.ComHcssHcssmobileTesting.Content.AddCostCodeTag.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView4.WRKORD02WorkOrderHash2' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.WRKORD02WorkOrderHash2Info, new RecordItemIndex(66));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.WRKORD02WorkOrderHash2.Touch();
            Delay.Milliseconds(500);
            
            // 10th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "10th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(67));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button5' at Center", repo.ComHcssHcssmobileTesting.Content.Button5Info, new RecordItemIndex(68));
            repo.ComHcssHcssmobileTesting.Content.Button5.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(69));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.UseSuggestedQuantities' at Center", repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantitiesInfo, new RecordItemIndex(70));
            repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantities.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Rework' at Center", repo.ComHcssHcssmobileTesting.Content.ReworkInfo, new RecordItemIndex(71));
            repo.ComHcssHcssmobileTesting.Content.Rework.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.AddCostCodeTag' at Center", repo.ComHcssHcssmobileTesting.Content.AddCostCodeTagInfo, new RecordItemIndex(72));
            repo.ComHcssHcssmobileTesting.Content.AddCostCodeTag.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView4.ST435Station435' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.ST435Station435Info, new RecordItemIndex(73));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.ST435Station435.Touch();
            Delay.Milliseconds(500);
            
            // 11th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "11th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(74));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button4' at Center", repo.ComHcssHcssmobileTesting.Content.Button4Info, new RecordItemIndex(75));
            repo.ComHcssHcssmobileTesting.Content.Button4.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button5' at Center", repo.ComHcssHcssmobileTesting.Content.Button5Info, new RecordItemIndex(76));
            repo.ComHcssHcssmobileTesting.Content.Button5.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.UseSuggestedQuantities' at Center", repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantitiesInfo, new RecordItemIndex(77));
            repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantities.Touch();
            Delay.Milliseconds(500);
            
            // 12th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "12th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(78));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button6' at Center", repo.ComHcssHcssmobileTesting.Content.Button6Info, new RecordItemIndex(79));
            repo.ComHcssHcssmobileTesting.Content.Button6.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.UseSuggestedQuantities' at Center", repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantitiesInfo, new RecordItemIndex(80));
            repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantities.Touch();
            Delay.Milliseconds(500);
            
            // 13th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "13th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(81));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.CheckBoxTM' at Center", repo.ComHcssHcssmobileTesting.Content.CheckBoxTMInfo, new RecordItemIndex(82));
            repo.ComHcssHcssmobileTesting.Content.CheckBoxTM.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button3' at Center", repo.ComHcssHcssmobileTesting.Content.Button3Info, new RecordItemIndex(83));
            repo.ComHcssHcssmobileTesting.Content.Button3.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.UseSuggestedQuantities' at Center", repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantitiesInfo, new RecordItemIndex(84));
            repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantities.Touch();
            Delay.Milliseconds(500);
            
            // 14th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "14th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(85));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button2' at Center", repo.ComHcssHcssmobileTesting.Content.Button2Info, new RecordItemIndex(86));
            repo.ComHcssHcssmobileTesting.Content.Button2.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.UseSuggestedQuantities' at Center", repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantitiesInfo, new RecordItemIndex(87));
            repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantities.Touch();
            Delay.Milliseconds(500);
            
            // 15th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "15th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(88));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button3' at Center", repo.ComHcssHcssmobileTesting.Content.Button3Info, new RecordItemIndex(89));
            repo.ComHcssHcssmobileTesting.Content.Button3.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.UseSuggestedQuantities' at Center", repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantitiesInfo, new RecordItemIndex(90));
            repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantities.Touch();
            Delay.Milliseconds(500);
            
            // 16th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "16th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(91));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button3' at Center", repo.ComHcssHcssmobileTesting.Content.Button3Info, new RecordItemIndex(92));
            repo.ComHcssHcssmobileTesting.Content.Button3.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(93));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(94));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(95));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.AddCostCodeTag' at Center", repo.ComHcssHcssmobileTesting.Content.AddCostCodeTagInfo, new RecordItemIndex(96));
            repo.ComHcssHcssmobileTesting.Content.AddCostCodeTag.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView4.Text5TH5thSt' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.Text5TH5thStInfo, new RecordItemIndex(97));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.Text5TH5thSt.Touch();
            Delay.Milliseconds(500);
            
            // 17th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "17th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(98));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button6' at Center", repo.ComHcssHcssmobileTesting.Content.Button6Info, new RecordItemIndex(99));
            repo.ComHcssHcssmobileTesting.Content.Button6.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(100));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'This work was for digging out rocks' on item 'ComHcssHcssmobileTesting.Content.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.Content.AndroidWidgetEditTextInfo, new RecordItemIndex(101));
            repo.ComHcssHcssmobileTesting.Content.AndroidWidgetEditText.Element.SetAttributeValue("Text", "This work was for digging out rocks");
            Delay.Milliseconds(100);
            
            // 18th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "18th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(102));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button2' at Center", repo.ComHcssHcssmobileTesting.Content.Button2Info, new RecordItemIndex(103));
            repo.ComHcssHcssmobileTesting.Content.Button2.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(104));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(105));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(106));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.UseSuggestedQuantities' at Center", repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantitiesInfo, new RecordItemIndex(107));
            repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantities.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.AddCostCodeTag' at Center", repo.ComHcssHcssmobileTesting.Content.AddCostCodeTagInfo, new RecordItemIndex(108));
            repo.ComHcssHcssmobileTesting.Content.AddCostCodeTag.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView4.ST460Station460' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.ST460Station460Info, new RecordItemIndex(109));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.ST460Station460.Touch();
            Delay.Milliseconds(500);
            
            // 19th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "19th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(110));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button4' at Center", repo.ComHcssHcssmobileTesting.Content.Button4Info, new RecordItemIndex(111));
            repo.ComHcssHcssmobileTesting.Content.Button4.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(112));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(113));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            // 20th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "20th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(114));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button8' at Center", repo.ComHcssHcssmobileTesting.Content.Button8Info, new RecordItemIndex(115));
            repo.ComHcssHcssmobileTesting.Content.Button8.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(116));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(117));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            // 21st Cost Code
            Report.Log(ReportLevel.Info, "Touch", "21st Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(118));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button9' at Center", repo.ComHcssHcssmobileTesting.Content.Button9Info, new RecordItemIndex(119));
            repo.ComHcssHcssmobileTesting.Content.Button9.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(120));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(121));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.AddCostCodeTag' at Center", repo.ComHcssHcssmobileTesting.Content.AddCostCodeTagInfo, new RecordItemIndex(122));
            repo.ComHcssHcssmobileTesting.Content.AddCostCodeTag.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView4.Text1ST1stSt' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.Text1ST1stStInfo, new RecordItemIndex(123));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView4.Text1ST1stSt.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.CheckBoxTM' at Center", repo.ComHcssHcssmobileTesting.Content.CheckBoxTMInfo, new RecordItemIndex(124));
            repo.ComHcssHcssmobileTesting.Content.CheckBoxTM.Touch();
            Delay.Milliseconds(500);
            
            // 22nd Cost Code
            Report.Log(ReportLevel.Info, "Touch", "22nd Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(125));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button2' at Center", repo.ComHcssHcssmobileTesting.Content.Button2Info, new RecordItemIndex(126));
            repo.ComHcssHcssmobileTesting.Content.Button2.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(127));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(128));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(129));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            // 23rd Cost Code
            Report.Log(ReportLevel.Info, "Touch", "23rd Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(130));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button1' at Center", repo.ComHcssHcssmobileTesting.Content.Button1Info, new RecordItemIndex(131));
            repo.ComHcssHcssmobileTesting.Content.Button1.Touch();
            Delay.Milliseconds(500);
            
            // 24th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "24th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(132));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button2' at Center", repo.ComHcssHcssmobileTesting.Content.Button2Info, new RecordItemIndex(133));
            repo.ComHcssHcssmobileTesting.Content.Button2.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.UseSuggestedQuantities' at Center", repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantitiesInfo, new RecordItemIndex(134));
            repo.ComHcssHcssmobileTesting.Content.UseSuggestedQuantities.Touch();
            Delay.Milliseconds(500);
            
            // 25th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "25th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.Content.SomeButton' at Center", repo.ComHcssHcssmobileTesting.Content.SomeButtonInfo, new RecordItemIndex(135));
            repo.ComHcssHcssmobileTesting.Content.SomeButton.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button2' at Center", repo.ComHcssHcssmobileTesting.Content.Button2Info, new RecordItemIndex(136));
            repo.ComHcssHcssmobileTesting.Content.Button2.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(137));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content.Button0' at Center", repo.ComHcssHcssmobileTesting.Content.Button0Info, new RecordItemIndex(138));
            repo.ComHcssHcssmobileTesting.Content.Button0.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Done2' at Center", repo.ComHcssHcssmobileTesting.Done2Info, new RecordItemIndex(139));
            repo.ComHcssHcssmobileTesting.Done2.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
