///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.ExportTimeCardToHDM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddCostCodes recording.
    /// </summary>
    [TestModule("5ad0a08c-2580-4e69-a871-980d60c75c45", ModuleType.Recording, 1)]
    public partial class AddCostCodes : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static AddCostCodes instance = new AddCostCodes();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddCostCodes()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddCostCodes Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetImageView' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetImageViewInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetImageView.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(1));
            Delay.Duration(30000, false);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '01-0910001' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(2));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "01-0910001");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Text010910001' at Center", repo.ComHcssHcssmobileTesting.Text010910001Info, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.Text010910001.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '02-0201004' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(4));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "02-0201004");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.Text020201004' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Text020201004Info, new RecordItemIndex(5));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Text020201004.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.Text020201004' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Text020201004Info, new RecordItemIndex(6));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Text020201004.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.Text020201004' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Text020201004Info, new RecordItemIndex(7));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Text020201004.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '02-0203001' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(8));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "02-0203001");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.DrillBlastRock' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.DrillBlastRockInfo, new RecordItemIndex(9));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.DrillBlastRock.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '02-0265010' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(10));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "02-0265010");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.LoadHaulRockDispose' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.LoadHaulRockDisposeInfo, new RecordItemIndex(11));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.LoadHaulRockDispose.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.LoadHaulRockDispose' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.LoadHaulRockDisposeInfo, new RecordItemIndex(12));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.LoadHaulRockDispose.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(13));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '03-0213003' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(14));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "03-0213003");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.FineGradePrepSubgrade' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.FineGradePrepSubgradeInfo, new RecordItemIndex(15));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.FineGradePrepSubgrade.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.FineGradePrepSubgrade' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.FineGradePrepSubgradeInfo, new RecordItemIndex(16));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.FineGradePrepSubgrade.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '04-0410050' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(17));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "04-0410050");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.FurnInst24RCP' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.FurnInst24RCPInfo, new RecordItemIndex(18));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.FurnInst24RCP.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.FurnInst24RCP' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.FurnInst24RCPInfo, new RecordItemIndex(19));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.FurnInst24RCP.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '06-0490050' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(20));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "06-0490050");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.Text060490050' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Text060490050Info, new RecordItemIndex(21));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Text060490050.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.BenchFinishInlet' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.BenchFinishInletInfo, new RecordItemIndex(22));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.BenchFinishInlet.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '07-0490050' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(23));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "07-0490050");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.BenchFinishInlet' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.BenchFinishInletInfo, new RecordItemIndex(24));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.BenchFinishInlet.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.BenchFinishInlet' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.BenchFinishInletInfo, new RecordItemIndex(25));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.BenchFinishInlet.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '09-0655000' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(26));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "09-0655000");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.MainlinePaving' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.MainlinePavingInfo, new RecordItemIndex(27));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.MainlinePaving.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '09-987870' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(28));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "09-987870");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.Linear1' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Linear1Info, new RecordItemIndex(29));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Linear1.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '10-0600100' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(30));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "10-0600100");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.FurnishHaulAC' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.FurnishHaulACInfo, new RecordItemIndex(31));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.FurnishHaulAC.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '11-0674010' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(32));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "11-0674010");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.PLANEASPHCONCPAV1' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.PLANEASPHCONCPAV1Info, new RecordItemIndex(33));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.PLANEASPHCONCPAV1.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '12-0653020' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(34));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "12-0653020");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.REFLPAVMRKTYIW4DOT' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.REFLPAVMRKTYIW4DOTInfo, new RecordItemIndex(35));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.REFLPAVMRKTYIW4DOT.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.REFLPAVMRKTYIW4DOT' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.REFLPAVMRKTYIW4DOTInfo, new RecordItemIndex(36));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.REFLPAVMRKTYIW4DOT.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.REFLPAVMRKTYIW4DOT' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.REFLPAVMRKTYIW4DOTInfo, new RecordItemIndex(37));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.REFLPAVMRKTYIW4DOT.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '9002xtr' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(38));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "9002xtr");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.Text9002XTR' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Text9002XTRInfo, new RecordItemIndex(39));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Text9002XTR.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '07-0490053' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(40));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "07-0490053");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.FurnishInstallTypeCInlet' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.FurnishInstallTypeCInletInfo, new RecordItemIndex(41));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.FurnishInstallTypeCInlet.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '09-0655011' on item 'ComHcssHcssmobileTesting.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1Info, new RecordItemIndex(42));
            repo.ComHcssHcssmobileTesting.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "09-0655011");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView3.Text090655011' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Text090655011Info, new RecordItemIndex(43));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView3.Text090655011.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Done1' at 52;53", repo.ComHcssHcssmobileTesting.Done1Info, new RecordItemIndex(44));
            repo.ComHcssHcssmobileTesting.Done1.Touch("52;53");
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
