///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.ExportTimeCardToHDM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddHours1stTenCostCodes recording.
    /// </summary>
    [TestModule("1cf34325-9379-4018-9c80-fcc0a3fc83ca", ModuleType.Recording, 1)]
    public partial class AddHours1stTenCostCodes : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static AddHours1stTenCostCodes instance = new AddHours1stTenCostCodes();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddHours1stTenCostCodes()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddHours1stTenCostCodes Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.0;

            Init();

            // 1st Cost Code
            Report.Log(ReportLevel.Info, "Touch", "1st Cost Code\r\nLongTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.Text010910001' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Text010910001Info, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Text010910001.LongTouch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(1));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(2));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            
            // 2nd Cost Code
            Report.Log(ReportLevel.Info, "Touch", "2nd Cost Code\r\nLongTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.RoughGradeSurface' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.RoughGradeSurfaceInfo, new RecordItemIndex(4));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.RoughGradeSurface.LongTouch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(5));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(6));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditTextInfo, new RecordItemIndex(7));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(8));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(9));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(10));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            
            // 3rd Cost Code
            Report.Log(ReportLevel.Info, "Touch", "3rd Cost Code\r\nLongTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.Text020201004' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Text020201004Info, new RecordItemIndex(11));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Text020201004.LongTouch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(12));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(13));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditTextInfo, new RecordItemIndex(14));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(15));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(16));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1Info, new RecordItemIndex(17));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(18));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(19));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(20));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            
            // 4th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "4th Cost Code\r\nLongTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.RoughGradeSurface1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.RoughGradeSurface1Info, new RecordItemIndex(21));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.RoughGradeSurface1.LongTouch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(22));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(23));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1Info, new RecordItemIndex(24));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(25));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(26));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(27));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            
            // 6th Cost Code (5th has no hours)
            Report.Log(ReportLevel.Info, "Touch", "6th Cost Code (5th has no hours)\r\nLongTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.Text020265010' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Text020265010Info, new RecordItemIndex(28));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Text020265010.LongTouch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditTextInfo, new RecordItemIndex(29));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(30));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(31));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1Info, new RecordItemIndex(32));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(33));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(34));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(35));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            
            // 7th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "7th Cost Code\r\nLongTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.Text0202650101' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Text0202650101Info, new RecordItemIndex(36));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Text0202650101.LongTouch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1Info, new RecordItemIndex(37));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(38));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(39));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(40));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            
            // 8th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "8th Cost Code\r\nLongTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.FineGradePrepSubgrade' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.FineGradePrepSubgradeInfo, new RecordItemIndex(41));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.FineGradePrepSubgrade.LongTouch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditTextInfo, new RecordItemIndex(42));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(43));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(44));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(45));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            
            // 9th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "9th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView87' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView87Info, new RecordItemIndex(46));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView87.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.ShowAttendanceCodes' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ShowAttendanceCodesInfo, new RecordItemIndex(47));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.ShowAttendanceCodes.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(48));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(49));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.SShowUp' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.SShowUpInfo, new RecordItemIndex(50));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.SShowUp.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(51));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(52));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.HHoliday' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.HHolidayInfo, new RecordItemIndex(53));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.HHoliday.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(54));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(55));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(56));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView86' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView86Info, new RecordItemIndex(57));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView86.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(58));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(59));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.DDown' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DDownInfo, new RecordItemIndex(60));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.DDown.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(61));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(62));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.SStandby' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.SStandbyInfo, new RecordItemIndex(63));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.SStandby.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(64));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(65));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(66));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            
            // 10th Cost Code
            Report.Log(ReportLevel.Info, "Touch", "10th Cost Code\r\nTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView88' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView88Info, new RecordItemIndex(67));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView88.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditTextInfo, new RecordItemIndex(68));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(69));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(70));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.EExcused' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.EExcusedInfo, new RecordItemIndex(71));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.EExcused.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(72));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(73));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.VVacation' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.VVacationInfo, new RecordItemIndex(74));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.VVacation.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(75));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(76));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(77));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView98' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView98Info, new RecordItemIndex(78));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView98.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditTextInfo, new RecordItemIndex(79));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(80));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(81));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.MMaintenance' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.MMaintenanceInfo, new RecordItemIndex(82));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.MMaintenance.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(83));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(84));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.RRepair' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.RRepairInfo, new RecordItemIndex(85));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.RRepair.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ButtonInfo, new RecordItemIndex(86));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Button1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1Info, new RecordItemIndex(87));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Button1.Touch();
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(88));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
