///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.ExportTimeCardToHDM
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddSchedules recording.
    /// </summary>
    [TestModule("1a6df0c2-ac87-422c-9984-4a2be5871f9c", ModuleType.Recording, 1)]
    public partial class AddSchedules : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static AddSchedules instance = new AddSchedules();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddSchedules()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddSchedules Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView105' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView105Info, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView105.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText2' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText2Info, new RecordItemIndex(1));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText2.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.ButtonOK' at Center", repo.ComHcssHcssmobileTesting.ButtonOKInfo, new RecordItemIndex(2));
            repo.ComHcssHcssmobileTesting.ButtonOK.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText3' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText3Info, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText3.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText3' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText3Info, new RecordItemIndex(4));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText3.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.ButtonOK' at Center", repo.ComHcssHcssmobileTesting.ButtonOKInfo, new RecordItemIndex(5));
            repo.ComHcssHcssmobileTesting.ButtonOK.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Break1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Break1Info, new RecordItemIndex(6));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Break1.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardBreakTimes.Text10Min' at Center", repo.ComHcssHcssmobileTesting.TimeCardBreakTimes.Text10MinInfo, new RecordItemIndex(7));
            repo.ComHcssHcssmobileTesting.TimeCardBreakTimes.Text10Min.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Break2' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.Break2Info, new RecordItemIndex(8));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Break2.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardBreakTimes.Text15Min' at Center", repo.ComHcssHcssmobileTesting.TimeCardBreakTimes.Text15MinInfo, new RecordItemIndex(9));
            repo.ComHcssHcssmobileTesting.TimeCardBreakTimes.Text15Min.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.ApplyToCrew' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.ApplyToCrewInfo, new RecordItemIndex(10));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.ApplyToCrew.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.ButtonYes' at Center", repo.ComHcssHcssmobileTesting.ButtonYesInfo, new RecordItemIndex(11));
            repo.ComHcssHcssmobileTesting.ButtonYes.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
