///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using WinForms = System.Windows.Forms;

namespace HJMobileAndroid.Recordings.ExportTimeCardToHDM
{
    public partial class RemoveTimeCardFromHDM
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        private void RemoveTimeCard(string connectionString)
        {
        	SqlConnection sqlConnection1 = new SqlConnection(connectionString);
			SqlCommand cmd = new SqlCommand();
			
			cmd.CommandText = "dbo.RemoveTimeCardFromHDM";
			cmd.CommandType = CommandType.StoredProcedure;
			                         
			cmd.Connection = sqlConnection1;

			sqlConnection1.Open();

			cmd.ExecuteNonQuery();

			sqlConnection1.Close();
        }

    }
}