///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.TimeCardProductionAnalysis
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddCrew recording.
    /// </summary>
    [TestModule("491409af-9b22-48c4-8b7b-e538fe1830be", ModuleType.Recording, 1)]
    public partial class AddCrew : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static AddCrew instance = new AddCrew();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddCrew()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddCrew Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.TapToAddCrew' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.TapToAddCrewInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.TapToAddCrew.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'ariyo,a' on item 'ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditTextInfo, new RecordItemIndex(1));
            repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText.Element.SetAttributeValue("Text", "ariyo,a");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content1.AyotoniAriyoFOREMAN' at Center", repo.ComHcssHcssmobileTesting.Content1.AyotoniAriyoFOREMANInfo, new RecordItemIndex(2));
            repo.ComHcssHcssmobileTesting.Content1.AyotoniAriyoFOREMAN.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'black,r' on item 'ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditTextInfo, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText.Element.SetAttributeValue("Text", "black,r");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content1.Relative' at Center", repo.ComHcssHcssmobileTesting.Content1.RelativeInfo, new RecordItemIndex(4));
            repo.ComHcssHcssmobileTesting.Content1.Relative.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'arnice,r' on item 'ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditTextInfo, new RecordItemIndex(5));
            repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText.Element.SetAttributeValue("Text", "arnice,r");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content1.RogerArniceLABOR' at Center", repo.ComHcssHcssmobileTesting.Content1.RogerArniceLABORInfo, new RecordItemIndex(6));
            repo.ComHcssHcssmobileTesting.Content1.RogerArniceLABOR.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content1.Equipment' at Center", repo.ComHcssHcssmobileTesting.Content1.EquipmentInfo, new RecordItemIndex(7));
            repo.ComHcssHcssmobileTesting.Content1.Equipment.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'tonka' on item 'ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditTextInfo, new RecordItemIndex(8));
            repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText.Element.SetAttributeValue("Text", "tonka");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content1.Link' at Center", repo.ComHcssHcssmobileTesting.Content1.LinkInfo, new RecordItemIndex(9));
            repo.ComHcssHcssmobileTesting.Content1.Link.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.AyotoniAriyo' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.AyotoniAriyoInfo, new RecordItemIndex(10));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.AyotoniAriyo.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText' at Center", repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditTextInfo, new RecordItemIndex(11));
            repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to 'sls' on item 'ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditTextInfo, new RecordItemIndex(12));
            repo.ComHcssHcssmobileTesting.Content1.AndroidWidgetEditText.Element.SetAttributeValue("Text", "sls");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Content1.Link' at Center", repo.ComHcssHcssmobileTesting.Content1.LinkInfo, new RecordItemIndex(13));
            repo.ComHcssHcssmobileTesting.Content1.Link.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.AndroidWidgetListView1.RogerArnice' at Center", repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.RogerArniceInfo, new RecordItemIndex(14));
            repo.ComHcssHcssmobileTesting.AndroidWidgetListView1.RogerArnice.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.Done3' at Center", repo.ComHcssHcssmobileTesting.Done3Info, new RecordItemIndex(15));
            repo.ComHcssHcssmobileTesting.Done3.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
