///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.TimeCardProductionAnalysis
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddHours recording.
    /// </summary>
    [TestModule("533b2817-5e44-474a-ba98-171a1c2592ff", ModuleType.Recording, 1)]
    public partial class AddHours : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static AddHours instance = new AddHours();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddHours()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddHours Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            // 1st Column Hours
            Report.Log(ReportLevel.Info, "Touch", "1st Column Hours\r\nTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextViewInfo, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView2' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView2Info, new RecordItemIndex(1));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView2.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView3' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView3Info, new RecordItemIndex(2));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView3.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.9S0.61' on item 'ComHcssHcssmobileTesting.TimeCardEntry.Text01'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01Info, new RecordItemIndex(3));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01.Element.SetAttributeValue("Text", "1.9S0.61");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(4));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView1' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView1Info, new RecordItemIndex(5));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView1.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView4' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView4Info, new RecordItemIndex(6));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView4.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.33D0.82' on item 'ComHcssHcssmobileTesting.TimeCardEntry.Text01'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01Info, new RecordItemIndex(7));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01.Element.SetAttributeValue("Text", "1.33D0.82");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(8));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            // 2nd Column Hours
            Report.Log(ReportLevel.Info, "Touch", "2nd Column Hours\r\nTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView21' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView21Info, new RecordItemIndex(9));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView21.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView19' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView19Info, new RecordItemIndex(10));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView19.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView18' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView18Info, new RecordItemIndex(11));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView18.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.23H0.02' on item 'ComHcssHcssmobileTesting.TimeCardEntry.Text01'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01Info, new RecordItemIndex(12));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01.Element.SetAttributeValue("Text", "1.23H0.02");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(13));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView20' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView20Info, new RecordItemIndex(14));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView20.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView17' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView17Info, new RecordItemIndex(15));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView17.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.88S0.62' on item 'ComHcssHcssmobileTesting.TimeCardEntry.Text01'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01Info, new RecordItemIndex(16));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01.Element.SetAttributeValue("Text", "1.88S0.62");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(17));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            // 3rd Column Hours
            Report.Log(ReportLevel.Info, "Touch", "3rd Column Hours\r\nTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView22' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView22Info, new RecordItemIndex(18));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView22.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView24' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView24Info, new RecordItemIndex(19));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView24.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView25' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView25Info, new RecordItemIndex(20));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView25.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.73E0.91' on item 'ComHcssHcssmobileTesting.TimeCardEntry.Text01'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01Info, new RecordItemIndex(21));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01.Element.SetAttributeValue("Text", "1.73E0.91");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(22));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView23' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView23Info, new RecordItemIndex(23));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView23.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView26' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView26Info, new RecordItemIndex(24));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView26.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.06M0.31' on item 'ComHcssHcssmobileTesting.TimeCardEntry.Text01'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01Info, new RecordItemIndex(25));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01.Element.SetAttributeValue("Text", "1.06M0.31");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(26));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            // 4th Colum Hours
            Report.Log(ReportLevel.Info, "Touch", "4th Colum Hours\r\nTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView43' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView43Info, new RecordItemIndex(27));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView43.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.36V0.44' on item 'ComHcssHcssmobileTesting.TimeCardEntry.Text01'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01Info, new RecordItemIndex(28));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01.Element.SetAttributeValue("Text", "1.36V0.44");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(29));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView42' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView42Info, new RecordItemIndex(30));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView42.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.4R0.18' on item 'ComHcssHcssmobileTesting.TimeCardEntry.Text01'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01Info, new RecordItemIndex(31));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Text01.Element.SetAttributeValue("Text", "1.4R0.18");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(32));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            // 5th Column Hours
            Report.Log(ReportLevel.Info, "Touch", "5th Column Hours\r\nTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndriodWidgetTextView1000' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndriodWidgetTextView1000Info, new RecordItemIndex(33));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndriodWidgetTextView1000.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.51T0.35' on item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditTextInfo, new RecordItemIndex(34));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText.Element.SetAttributeValue("Text", "1.51T0.35");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(35));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndriodWidgetTextView1001' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndriodWidgetTextView1001Info, new RecordItemIndex(36));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndriodWidgetTextView1001.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.5T0.46' on item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditTextInfo, new RecordItemIndex(37));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText.Element.SetAttributeValue("Text", "1.5T0.46");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(38));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch Gestures", "Swipe gesture with direction 'Left (180°)' starting from 'Center' with distance '5.0' with swipe duration'500ms' and step count '0' on item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditTextInfo, new RecordItemIndex(39));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText.Swipe(Location.Center, ValueConverter.ArgumentFromString<Ranorex.Core.Recorder.Touch.GestureDirection>("SwipeDirection", "Left (180°)"), ValueConverter.ArgumentFromString<Ranorex.Core.Distance>("Distance", "5.0"), ValueConverter.ArgumentFromString<Ranorex.Duration>("SwipeDuration", "500ms"), 0);
            Delay.Milliseconds(500);
            
            // 6th Colum Hours
            Report.Log(ReportLevel.Info, "Touch", "6th Colum Hours\r\nTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView44' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView44Info, new RecordItemIndex(40));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView44.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.49A0.15' on item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditTextInfo, new RecordItemIndex(41));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText.Element.SetAttributeValue("Text", "1.49A0.15");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(42));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView45' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView45Info, new RecordItemIndex(43));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView45.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.05W0.25' on item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditTextInfo, new RecordItemIndex(44));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText.Element.SetAttributeValue("Text", "1.05W0.25");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(45));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            // 7Th Colunm Hours
            Report.Log(ReportLevel.Info, "Touch", "7Th Colunm Hours\r\nTouch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView65' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView65Info, new RecordItemIndex(46));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView65.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.15W0.02' on item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1Info, new RecordItemIndex(47));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "1.15W0.02");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(48));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView64' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView64Info, new RecordItemIndex(49));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetTextView64.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '1.43' on item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1'.", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1Info, new RecordItemIndex(50));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetEditText1.Element.SetAttributeValue("Text", "1.43");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.Done' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.DoneInfo, new RecordItemIndex(51));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.Done.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
