///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HJMobileAndroid.Recordings.TimeCardProductionAnalysis
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateSecondTimeCard recording.
    /// </summary>
    [TestModule("54cc62df-0083-45a5-821a-c14779cfb63f", ModuleType.Recording, 1)]
    public partial class ValidateSecondTimeCard : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HJMobileAndroid.HJMobileAndroidRepository repository.
        /// </summary>
        public static HJMobileAndroid.HJMobileAndroidRepository repo = HJMobileAndroid.HJMobileAndroidRepository.Instance;

        static ValidateSecondTimeCard instance = new ValidateSecondTimeCard();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateSecondTimeCard()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateSecondTimeCard Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.4")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.0;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetButton2' at Center", repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetButton2Info, new RecordItemIndex(0));
            repo.ComHcssHcssmobileTesting.TimeCardEntry.AndroidWidgetButton2.Touch();
            Delay.Milliseconds(1000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(1));
            Delay.Duration(30000, false);
            
            // Total Dollars 1st Line
            Report.Log(ReportLevel.Info, "Validation", "Total Dollars 1st Line\r\nValidating AttributeEqual (Text='498.42') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Text49842'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text49842Info, new RecordItemIndex(2));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text49842Info, "Text", "498.42");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='5492.34') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Text549234'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text549234Info, new RecordItemIndex(3));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text549234Info, "Text", "5492.34");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='($4,993.92)') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar499392'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar499392Info, new RecordItemIndex(4));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar499392Info, "Text", "($4,993.92)");
            Delay.Milliseconds(100);
            
            // 2nd Line
            Report.Log(ReportLevel.Info, "Validation", "2nd Line\r\nValidating AttributeEqual (Text='3538.84') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Text353884'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text353884Info, new RecordItemIndex(5));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text353884Info, "Text", "3538.84");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='3462.58') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Text346258'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text346258Info, new RecordItemIndex(6));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text346258Info, "Text", "3462.58");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='$76.26') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar76_26'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar76_26Info, new RecordItemIndex(7));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar76_26Info, "Text", "$76.26");
            Delay.Milliseconds(100);
            
            // 3rd Line
            Report.Log(ReportLevel.Info, "Validation", "3rd Line\r\nValidating AttributeEqual (Text='8655.91') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Text865591'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text865591Info, new RecordItemIndex(8));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text865591Info, "Text", "8655.91");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='7582.91') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Text758291'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text758291Info, new RecordItemIndex(9));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text758291Info, "Text", "7582.91");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='$1,073.00') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar107300'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar107300Info, new RecordItemIndex(10));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar107300Info, "Text", "$1,073.00");
            Delay.Milliseconds(100);
            
            // 4th Line
            Report.Log(ReportLevel.Info, "Validation", "4th Line\r\nValidating AttributeEqual (Text='0.00') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Text0001'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text0001Info, new RecordItemIndex(11));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text0001Info, "Text", "0.00");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='4757.11') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Copy_of_Text00012'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Copy_of_Text00012Info, new RecordItemIndex(12));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Copy_of_Text00012Info, "Text", "4757.11");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='($4,757.11)') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Copy_of_Text00013'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Copy_of_Text00013Info, new RecordItemIndex(13));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Copy_of_Text00013Info, "Text", "($4,757.11)");
            Delay.Milliseconds(100);
            
            // 5th Line
            Report.Log(ReportLevel.Info, "Validation", "5th Line\r\nValidating AttributeEqual (Text='13751.59') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Text1375159'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text1375159Info, new RecordItemIndex(14));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text1375159Info, "Text", "13751.59");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='5183.80') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Text518380'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text518380Info, new RecordItemIndex(15));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Text518380Info, "Text", "5183.80");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='$8,567.79') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar856779'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar856779Info, new RecordItemIndex(16));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar856779Info, "Text", "$8,567.79");
            Delay.Milliseconds(100);
            
            // 6th Line
            Report.Log(ReportLevel.Info, "Validation", "6th Line\r\nValidating AttributeEqual (Text='3605.55') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Copy_of_Text1156'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Copy_of_Text1156Info, new RecordItemIndex(17));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Copy_of_Text1156Info, "Text", "3605.55");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='3605.55') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.Copy_of_Text11515'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Copy_of_Text11515Info, new RecordItemIndex(18));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.Copy_of_Text11515Info, "Text", "3605.55");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='$0.00') on item 'ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar000'.", repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar000Info, new RecordItemIndex(19));
            Validate.Attribute(repo.ComHcssHcssmobileTesting.AndroidWidgetListView5.TextDollar000Info, "Text", "$0.00");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
